[project]
name = "cra-water-availability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.4",
    "plotly>=7.1.0",
    "streamlit>=1.64.0",
    "streamlit-folium>=0.27.4",
]

[dependency-groups]
dev = [
    "isort>=9.0.1",
]
